// EmailJS Configuration for EMI Calculator
// 
// To set up EmailJS for the EMI Calculator:
// 
// 1. Go to https://www.emailjs.com/
// 2. Create an account and set up a service (Gmail, Outlook, etc.)
// 3. Create an email template with the following variables:
//    - {{to_email}} - Recipient email
//    - {{to_name}} - Recipient name
//    - {{subject}} - Email subject
//    - {{message}} - Email content
// 
// 4. Replace the placeholders in EMICalculator.tsx with your actual values:

export const EMAILJS_CONFIG = {
  PUBLIC_KEY: 'UJFEGLg5cPdJxgAT1', // EmailJS public key
  SERVICE_ID: 'service_6p4xblf',    // EmailJS service ID
  TEMPLATE_ID: 'template_z8h2vwg',  // EmailJS template ID
};

// Sample EmailJS Template Structure:
// 
// Subject: {{subject}}
// 
// Dear {{to_name}},
// 
// {{message}}
// 
// Best regards,
// Prime Vista Homes Team
// 
// ---
// This email was automatically generated by our EMI Calculator.
// If you have any questions, please contact our support team.

// Instructions for implementation:
// 1. Update the EMAILJS_CONFIG values above
// 2. Replace the placeholders in EMICalculator.tsx:
//    - Replace 'YOUR_EMAILJS_PUBLIC_KEY' with EMAILJS_CONFIG.PUBLIC_KEY
//    - Replace 'YOUR_SERVICE_ID' with EMAILJS_CONFIG.SERVICE_ID  
//    - Replace 'YOUR_TEMPLATE_ID' with EMAILJS_CONFIG.TEMPLATE_ID
// 3. Import this config in EMICalculator.tsx if needed
